owners = ["poljar", "github:matrix-org:rust"]

pre-release-commit-message = "chore: Release matrix-sdk version {{version}}"
pre-release-hook = ["towncrier", "build", "--config=../../towncrier.toml", "--dir=./", "--version={{version}}", "--yes"]

sign-tag = true
tag-message = "Release {{crate_name}} version {{version}}"
tag-name = "{{prefix}}{{version}}"
shared-version = true

# Necessary to work with jujutsu
allow-branch = ["HEAD", "release-*"]
