name: Lint dependencies (for licences, allowed sources, banned dependencies, vulnerabilities)
on:
  pull_request:
    paths:
      - '**/Cargo.toml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions: {}

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false
    - uses: EmbarkStudios/cargo-deny-action@bb137d7af7e4fb67e5f82a49c4fce4fad40782fe # v2.0.20
