name: Detects unused dependencies
on:
  pull_request: { branches: "*" }

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: Machete
        uses: bnjbvr/cargo-machete@2e2703d664c176156a22936b9203c38cc7a273dd
