name: Rust version

on:
  workflow_dispatch:
  push:
    branches: ["main", "features/**", "release-**"]
  pull_request:
    branches: ["main", "features/**", "release-**"]

permissions: {}

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
    - uses: taiki-e/install-action@711e1c3275189d76dcc4d34ddea63bf96ac49090 # cargo-hack
      with:
        tool: cargo-hack
    - run: cargo hack check --rust-version --workspace --all-targets
